import { AnalyticsSnapshot, ImprovementInitiative, RootCauseAnalysis } from '@core/models';

export const CONTINUOUS_IMPROVEMENT_SNAPSHOTS: readonly AnalyticsSnapshot[] = [
  {
    id: 'snapshot-2024-05',
    title: '2024年5月 品質レビュー',
    periodStart: '2024-05-01',
    periodEnd: '2024-05-31',
    summary: 'API安定化とレビュー手戻りに関する指摘が中心です。',
    recurrenceRate: 0.37,
    recurrenceDelta: -0.12,
    totalFeedback: 82,
    severeCount: 19,
    metrics: [
      { label: 'MTTR', value: '6.4時間', delta: -0.18 },
      { label: '重大障害', value: '19件', delta: -0.22 },
      { label: '一次回答', value: '42分', delta: -0.11 },
    ],
    topErrors: [
      {
        id: 'api-timeout',
        title: 'API タイムアウト',
        category: 'バックエンド',
        severity: 'high',
        frequency: 18,
        changeRatio: -0.18,
        description: 'デプロイ直後に接続プールが枯渇しレスポンスが停止しました。',
        causeHint: 'リリースチェックリストの欠落と監視閾値の遅延調整が背景です。',
        recentExamples: ['CARD-102', 'INC-58'],
      },
      {
        id: 'regression-ui',
        title: 'レビューコメントの見落とし',
        category: 'UX',
        severity: 'medium',
        frequency: 14,
        changeRatio: 0.08,
        description: 'レビュー観点が属人化し同じUI指摘が再発しました。',
        causeHint: 'レビュー指標の明文化不足とナレッジ分散が原因です。',
        recentExamples: ['CARD-089', 'CARD-143'],
      },
      {
        id: 'handoff-gap',
        title: '担当者引継ぎの遅延',
        category: 'プロセス',
        severity: 'high',
        frequency: 11,
        changeRatio: 0.12,
        description: '夜間リリースの引継ぎが形式的で復旧が遅れました。',
        causeHint: '責任者が曖昧で教育フローが不足しています。',
        recentExamples: ['POSTMORTEM-012'],
      },
    ],
  },
  {
    id: 'snapshot-2024-04',
    title: '2024年4月 品質レビュー',
    periodStart: '2024-04-01',
    periodEnd: '2024-04-30',
    summary: 'リリース直後の障害がピークを迎えた期間です。',
    recurrenceRate: 0.49,
    recurrenceDelta: 0.07,
    totalFeedback: 96,
    severeCount: 27,
    metrics: [
      { label: 'MTTR', value: '7.8時間', delta: 0.09 },
      { label: '重大障害', value: '27件', delta: 0.14 },
      { label: '一次回答', value: '58分', delta: 0.05 },
    ],
    topErrors: [
      {
        id: 'api-timeout',
        title: 'API タイムアウト',
        category: 'バックエンド',
        severity: 'critical',
        frequency: 24,
        changeRatio: 0.32,
        description: '負荷試験が不足し本番でスロークエリが多発しました。',
        causeHint: '性能門番が機能せず設定差分の検知が遅れました。',
        recentExamples: ['CARD-061', 'INC-044'],
      },
      {
        id: 'missing-test',
        title: '自動テスト未整備',
        category: '品質保証',
        severity: 'medium',
        frequency: 16,
        changeRatio: 0.18,
        description: 'レガシー領域の自動テストが存在せず回帰が多発しました。',
        causeHint: '優先度の判断基準が曖昧で着手されませんでした。',
        recentExamples: ['CARD-072'],
      },
    ],
  },
];

export const CONTINUOUS_IMPROVEMENT_ANALYSES: readonly RootCauseAnalysis[] = [
  {
    id: 'analysis-2024-05',
    snapshotId: 'snapshot-2024-05',
    focusQuestion: 'なぜ API タイムアウトが繰り返されるのか?',
    summary: 'リリース手順の形骸化と監視閾値の遅延調整が主要因です。',
    nodes: [
      {
        id: 'node-root-may',
        parentId: null,
        depth: 0,
        statement: 'なぜ重要リリースでAPIタイムアウトが再発するのか',
        confidence: 0.72,
        state: 'confirmed',
        evidence: ['CARD-102', 'INC-58'],
        recommendedMetrics: ['timeout_rate', 'release_checklist_adoption'],
        tone: 'neutral',
      },
      {
        id: 'node-1a',
        parentId: 'node-root-may',
        depth: 1,
        statement: 'リリースチェックリストの遵守率が低下している',
        confidence: 0.63,
        state: 'confirmed',
        evidence: ['deploy-review-18'],
        recommendedMetrics: ['release_checklist_adoption'],
        tone: 'direct',
      },
      {
        id: 'node-1b',
        parentId: 'node-root-may',
        depth: 1,
        statement: '監視アラートの閾値が旧構成のままで検知が遅れる',
        confidence: 0.6,
        state: 'proposed',
        evidence: ['sre-weekly-22'],
        recommendedMetrics: ['alert_time_to_ack'],
        tone: 'neutral',
      },
      {
        id: 'node-2a',
        parentId: 'node-1a',
        depth: 2,
        statement: 'ドキュメント更新の責任者が曖昧で改訂が遅延している',
        confidence: 0.58,
        state: 'needs-review',
        evidence: ['handoff-review'],
        recommendedMetrics: ['runbook_freshness_index'],
        tone: 'direct',
      },
    ],
    suggestions: [
      {
        id: 'action-runbook',
        nodeId: 'node-2a',
        title: 'リリースチェックリストをワークフローに組み込む',
        summary: 'チェックリストを刷新し承認ゲートを追加する。',
        description: 'SREと開発リードでテンプレートを更新し、承認ステップを必須化します。',
        status: 'pending',
        effort: 'medium',
        impactScore: 4,
        ownerRole: 'SREリード',
        dueInDays: 10,
        targetStatusId: 'todo',
        labelIds: ['backend'],
        initiativeId: 'initiative-stability',
      },
      {
        id: 'action-alert',
        nodeId: 'node-1b',
        title: '監視閾値のチューニングワークショップ',
        summary: '過去データを分析し閾値を調整する。',
        description:
          'QAとSREでワークショップを開催し通知レベルと自動エスカレーションを設計します。',
        status: 'pending',
        effort: 'low',
        impactScore: 3,
        ownerRole: 'QAマネージャー',
        dueInDays: 7,
        targetStatusId: 'in-progress',
        labelIds: ['backend', 'ai'],
        initiativeId: 'initiative-stability',
      },
      {
        id: 'action-education',
        nodeId: 'node-1a',
        title: '引継ぎレビューのライブトレーニング',
        summary: '過去障害を教材にした演習を実施する。',
        description: 'ケーススタディを共有し採点基準を可視化します。',
        status: 'converted',
        effort: 'medium',
        impactScore: 5,
        ownerRole: '開発マネージャー',
        dueInDays: 0,
        targetStatusId: 'in-progress',
        labelIds: ['backend'],
        initiativeId: 'initiative-stability',
        createdCardId: 'card-training-01',
      },
    ],
  },
  {
    id: 'analysis-2024-04',
    snapshotId: 'snapshot-2024-04',
    focusQuestion: 'なぜ4月は重大障害が集中したのか?',
    summary: '性能試験の抜け漏れとテスト優先順位の判断遅延が影響しました。',
    nodes: [
      {
        id: 'node-root-apr',
        parentId: null,
        depth: 0,
        statement: 'なぜ4月の重大障害は前月比で増加したのか',
        confidence: 0.69,
        state: 'confirmed',
        evidence: ['INC-044', 'INC-038'],
        recommendedMetrics: ['incident_count', 'mttr'],
        tone: 'neutral',
      },
      {
        id: 'node-apr-1',
        parentId: 'node-root-apr',
        depth: 1,
        statement: '性能テストがスプリント計画に組み込まれていない',
        confidence: 0.61,
        state: 'confirmed',
        evidence: ['qa-retro'],
        recommendedMetrics: ['performance_test_coverage'],
        tone: 'direct',
      },
      {
        id: 'node-apr-2',
        parentId: 'node-root-apr',
        depth: 1,
        statement: '自動テスト整備の優先順位判断が曖昧',
        confidence: 0.52,
        state: 'needs-review',
        evidence: ['retro-2024-03'],
        recommendedMetrics: ['automated_test_ratio'],
        tone: 'neutral',
      },
    ],
    suggestions: [
      {
        id: 'action-performance',
        nodeId: 'node-apr-1',
        title: '性能テストのスプリント定常化',
        summary: 'スプリント計画に負荷試験タスクを追加する。',
        description: '性能門番を明確化しストーリーポイントを確保します。',
        status: 'pending',
        effort: 'high',
        impactScore: 4,
        ownerRole: 'テックリード',
        dueInDays: 14,
        targetStatusId: 'todo',
        labelIds: ['backend'],
        initiativeId: 'initiative-performance',
      },
    ],
  },
];

export const CONTINUOUS_IMPROVEMENT_INITIATIVES: readonly ImprovementInitiative[] = [
  {
    id: 'initiative-stability',
    name: 'API 安定化プログラム',
    owner: '田中太郎',
    status: 'on-track',
    health: 'watch',
    startDate: '2024-03-01',
    targetMetric: 'タイムアウト率 1% 未満',
    summary: 'SREと開発が横断で再発防止を進める取り組みです。',
    progress: [
      {
        id: 'log-stability-1',
        timestamp: '2024-04-15T09:00:00Z',
        status: '調査完了',
        notes: '主要因を3件に絞り込みました。',
        metrics: { recurrence: '52%' },
      },
      {
        id: 'log-stability-2',
        timestamp: '2024-05-10T10:00:00Z',
        status: '対策実施中',
        notes: 'チェックリスト草案をレビュー中です。',
        metrics: { recurrence: '42%' },
      },
    ],
  },
  {
    id: 'initiative-performance',
    name: 'パフォーマンス最適化作戦',
    owner: '佐藤花子',
    status: 'completed',
    health: 'good',
    startDate: '2024-01-10',
    targetMetric: 'P95 レスポンス 1.2秒 以下',
    summary: '性能計測基盤の整備と自動化を推進しました。',
    progress: [
      {
        id: 'log-performance-1',
        timestamp: '2024-02-05T08:30:00Z',
        status: '自動計測導入',
        notes: 'Grafana ダッシュボードを公開。',
        metrics: { p95: '1.35s' },
      },
      {
        id: 'log-performance-2',
        timestamp: '2024-04-05T12:00:00Z',
        status: '成果検証',
        notes: 'P95 が 1.18s まで改善しました。',
        metrics: { p95: '1.18s' },
      },
    ],
  },
];
