name: Auto Evolve Roles
on:
  schedule: [{ cron: "0 3 * * 1" }] # JST 月曜 12:00 -> UTC 03:00 目安で運用
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  evolve:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with: { python-version: "3.11" }

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyYAML

      - name: Install deps (jq)
        run: |
          sudo apt-get update -y
          sudo apt-get install -y jq

      - name: Aggregate metrics
        run: |
          chmod +x scripts/_metrics.sh || true
          python3 scripts/collect_metrics.py || true

      - name: Optimize & propose
        run: |
          python3 scripts/role_optimizer.py

      - name: Render evidence (graph/plan/rollback)
        run: |
          python3 scripts/render_role_changes.py --proposals codex_output/auto_evolve/proposals.json

      - name: Create PR
        uses: peter-evans/create-pull-request@v6
        with:
          title: "Auto-Evolve: role consolidation/route optimization proposals"
          branch: auto-evolve/proposal-${{ github.run_id }}
          commit-message: "auto-evolve: policy-driven proposals"
          body: |
            This PR is auto-generated by **Auto-Evolve**.
            - Evidence: `codex_output/auto_evolve/proposals.json`
            - Graph: `codex_output/auto_evolve/graph_before_after.md`
            - A/B plan: `codex_output/auto_evolve/experiment_plan.md`
            - Rollback: `codex_output/auto_evolve/rollback.md`
