name: Codex Auto Dev

on:
  workflow_dispatch:   # 手動実行
  issues:              # Issue起票（新規作成時）
    types: [opened]
  issue_comment:       # Issueコメントでトリガー
    types: [created]

jobs:
  codex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Codex
        run: npm install -g codex-cli

      - name: Run Codex translator → requirements analyst → detail designer → planner pipeline
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # イベント種別で入力を切り替え
          if [ "${{ github.event_name }}" = "issues" ]; then
            TASK_INPUT="${{ github.event.issue.title }}: ${{ github.event.issue.body }}"
          elif [ "${{ github.event_name }}" = "issue_comment" ]; then
            TASK_INPUT="Comment on issue #${{ github.event.issue.number }}: ${{ github.event.comment.body }}"
          else
            TASK_INPUT="Manual trigger: Please implement the requested feature."
          fi

          echo "TASK_INPUT: $TASK_INPUT"
          mkdir -p codex_output

          TRANSLATOR_OUTPUT="$(codex translator --task "$TASK_INPUT")"
          printf '%s\n' "$TRANSLATOR_OUTPUT" > codex_output/translator.md

          REQUIREMENTS_OUTPUT="$(codex requirements_analyst --task "$TRANSLATOR_OUTPUT")"
          printf '%s\n' "$REQUIREMENTS_OUTPUT" > codex_output/requirements_analyst.md

          DETAIL_DESIGN_OUTPUT="$(codex detail_designer --task "$REQUIREMENTS_OUTPUT")"
          printf '%s\n' "$DETAIL_DESIGN_OUTPUT" > codex_output/detail_designer.md

          PLAN_OUTPUT="$(codex planner --task "$DETAIL_DESIGN_OUTPUT")"
          printf '%s\n' "$PLAN_OUTPUT" > codex_output/planner.md
