name: Codex Auto Dev

on:
  workflow_dispatch:   # 手動実行
  issues:              # Issue起票（新規作成時）
    types: [opened]
  issue_comment:       # Issueコメントでトリガー
    types: [created]

jobs:
  codex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Codex CLI
        run: npm install -g @openai/codex

      - name: Run Codex translator → requirements analyst → detail designer → planner pipeline
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          # イベント種別で入力を切り替え。Codex パイプラインには生のテキストのみを渡す。
          if [ "${{ github.event_name }}" = "issues" ]; then
            RAW_TASK_INPUT="${{ github.event.issue.title }}: ${{ github.event.issue.body }}"
          elif [ "${{ github.event_name }}" = "issue_comment" ]; then
            RAW_TASK_INPUT="Comment on issue #${{ github.event.issue.number }}: ${{ github.event.comment.body }}"
          else
            RAW_TASK_INPUT="Manual trigger: Please implement the requested feature."
          fi

          echo "TASK_INPUT: $RAW_TASK_INPUT"
          mkdir -p codex_output
          if ! command -v codex >/dev/null 2>&1; then
            echo "Codex CLI not installed correctly" >&2
            exit 1
          fi

          scripts/run_codex_pipeline.sh "$RAW_TASK_INPUT"

      - name: Upload Codex outputs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: codex-agent-outputs
          path: codex_output
