name: Lint

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - '.eslintrc*'
      - 'package*.json'
      - '.github/workflows/lint.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - '.eslintrc*'
      - 'package*.json'
      - '.github/workflows/lint.yml'

concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  eslint:
    if: ${{ github.event_name == 'push' || !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
      pull-requests: read
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint
