name: Lint

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - '.eslintrc*'
      - 'package*.json'
      - '.github/workflows/lint.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - '.eslintrc*'
      - 'package*.json'
      - '.github/workflows/lint.yml'

concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  eslint:
    if: ${{ github.event_name == 'push' || !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
      pull-requests: read
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (with cache)
        if: ${{ hashFiles('package-lock.json','frontend/package-lock.json') != '' }}
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: |
            package-lock.json
            frontend/package-lock.json

      - name: Setup Node (no cache)
        if: ${{ hashFiles('package-lock.json','frontend/package-lock.json') == '' }}
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint
