name: Secret Scan

on:
  push:
    branches: [ main ]
  pull_request:

concurrency:
  group: secret-scan-${{ github.ref }}
  cancel-in-progress: true

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --source=. --no-git --redact
