name: Secret Scan

on:
  push:
    branches: [ main ]
  pull_request:

concurrency:
  group: secret-scan-${{ github.ref }}
  cancel-in-progress: true

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Install gitleaks
        env:
          GITLEAKS_VERSION: 8.18.4
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          set -euo pipefail
          mkdir -p "$HOME/.local/bin"
          curl -sSLo gitleaks.tar.gz \
            -H "Authorization: Bearer ${GITHUB_TOKEN}" \
            -H "Accept: application/octet-stream" \
            "https://github.com/gitleaks/gitleaks/releases/download/v${GITLEAKS_VERSION}/gitleaks_${GITLEAKS_VERSION}_linux_x64.tar.gz"
          tar -xzf gitleaks.tar.gz gitleaks
          rm gitleaks.tar.gz
          chmod +x gitleaks
          mv gitleaks "$HOME/.local/bin/gitleaks"
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"

      - name: Run gitleaks
        run: |
          set -euo pipefail
          gitleaks version
          gitleaks detect --source=. --no-git --redact
