name: Secret Scan

on:
  push:
    branches: [ main ]
  pull_request:

concurrency:
  group: secret-scan-${{ github.ref }}
  cancel-in-progress: true

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Install gitleaks
        run: |
          curl -sSfL https://raw.githubusercontent.com/gitleaks/gitleaks/v8.18.4/install.sh | sh -s -- -b /usr/local/bin

      - name: Run gitleaks
        run: |
          gitleaks detect --source=. --no-git --redact
